dist: trusty
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9876 http://localhost &
language: node_js
node_js:
  - "7"

before_script:
  npm install typescript@2.3.4 -g